//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class Pass1<R,A> implements GJVisitor<R,A> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //

   public ArrayList<InstrNode> dataSets = new ArrayList<>(); // stores use and def sets of each instruction
   int instr = 0; // index of an instruction (i.e., instructions are numbered from 0)

   public HashMap<String, Integer> labelIdx = new HashMap<>(); // label to instruction number/index
   boolean moveFlag = false;
   boolean callFlag = false;
   
   public R visit(NodeList n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeListOptional n, A argu) {
      if ( n.present() ) {
         R _ret=null;
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
            _count++;
         }
         return _ret;
      }
      else
         return null;
   }

   public R visit(NodeOptional n, A argu) { // the node in the NodeOptional can only be label according to the grammar
      if ( n.present() ) {
         String _label = (String)n.node.accept(this,argu);
         labelIdx.put(_label, instr);
      }
      return null;
   }

   public R visit(NodeSequence n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeToken n, A argu) { return null; }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> "MAIN"
    * f1 -> StmtList()
    * f2 -> "END"
    * f3 -> ( Procedure() )*
    * f4 -> <EOF>
    */
   public R visit(Goal n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ( ( Label() )? Stmt() )*
    */
   public R visit(StmtList n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Label()
    * f1 -> "["
    * f2 -> IntegerLiteral()
    * f3 -> "]"
    * f4 -> StmtExp()
    */
   public R visit(Procedure n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> NoOpStmt()
    *       | ErrorStmt()
    *       | CJumpStmt()
    *       | JumpStmt()
    *       | HStoreStmt()
    *       | HLoadStmt()
    *       | MoveStmt()
    *       | PrintStmt()
    */
   public R visit(Stmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);

      ++instr;
      return _ret;
   }

   /**
    * f0 -> "NOOP"
    */
   public R visit(NoOpStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);

      dataSets.add(new InstrNode());
      return _ret;
   }

   /**
    * f0 -> "ERROR"
    */
   public R visit(ErrorStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);

      dataSets.add(new InstrNode());
      return _ret;
   }

   /**
    * f0 -> "CJUMP"
    * f1 -> Temp()
    * f2 -> Label()
    */
   public R visit(CJumpStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String t = (String)n.f1.accept(this, argu);
      n.f2.accept(this, argu);

      InstrNode currDataSets = new InstrNode();
      currDataSets.use.add(t);
      dataSets.add(currDataSets);
      return _ret;
   }

   /**
    * f0 -> "JUMP"
    * f1 -> Label()
    */
   public R visit(JumpStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);

      dataSets.add(new InstrNode());
      return _ret;
   }

   /**
    * f0 -> "HSTORE"
    * f1 -> Temp()
    * f2 -> IntegerLiteral()
    * f3 -> Temp()
    */
   public R visit(HStoreStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String t1 = (String)n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      String t2 = (String)n.f3.accept(this, argu);

      InstrNode currDataSets = new InstrNode();
      currDataSets.use.add(t1);
      currDataSets.use.add(t2);
      dataSets.add(currDataSets);
      return _ret;
   }

   /**
    * f0 -> "HLOAD"
    * f1 -> Temp()
    * f2 -> Temp()
    * f3 -> IntegerLiteral()
    */
   public R visit(HLoadStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String t1 = (String)n.f1.accept(this, argu);
      String t2 = (String)n.f2.accept(this, argu);
      n.f3.accept(this, argu);

      InstrNode currDataSets = new InstrNode();
      currDataSets.def.add(t1);
      currDataSets.use.add(t2);
      dataSets.add(currDataSets);
      return _ret;
   }

   /**
    * f0 -> "MOVE"
    * f1 -> Temp()
    * f2 -> Exp()
    */
   public R visit(MoveStmt n, A argu) {
      InstrNode currDataSets = new InstrNode();
      dataSets.add(currDataSets);

      R _ret=null;
      n.f0.accept(this, argu);
      String t1 = (String)n.f1.accept(this, argu);

      moveFlag = true;
      n.f2.accept(this, argu);
      moveFlag = false;

      currDataSets.def.add(t1);
      return _ret;
   }

   /**
    * f0 -> "PRINT"
    * f1 -> SimpleExp()
    */
   public R visit(PrintStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String _simpleExp = (String)n.f1.accept(this, argu);

      InstrNode currDataSets = new InstrNode();
      if (_simpleExp.startsWith("TEMP ")) {
          currDataSets.use.add(_simpleExp);
      }
      dataSets.add(currDataSets);
      return _ret;
   }

   /**
    * f0 -> Call()
    *       | HAllocate()
    *       | BinOp()
    *       | SimpleExp()
    */
   public R visit(Exp n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "BEGIN"
    * f1 -> StmtList()
    * f2 -> "RETURN"
    * f3 -> SimpleExp()
    * f4 -> "END"
    */
   public R visit(StmtExp n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      String _simpleExp = (String)n.f3.accept(this, argu);
      n.f4.accept(this, argu);

      InstrNode currDataSets = new InstrNode();
      if (_simpleExp.startsWith("TEMP ")) {
          currDataSets.use.add(_simpleExp);
      }
      dataSets.add(currDataSets);
      ++instr;
      return _ret;
   }

   /**
    * f0 -> "CALL"
    * f1 -> SimpleExp()
    * f2 -> "("
    * f3 -> ( Temp() )*
    * f4 -> ")"
    */
   public R visit(Call n, A argu) {
      InstrNode currDataSets = dataSets.get(instr);

      R _ret=null;
      n.f0.accept(this, argu);
      String _simpleExp = (String)n.f1.accept(this, argu);
      n.f2.accept(this, argu);

      callFlag = true;
      n.f3.accept(this, argu);
      callFlag = false;

      n.f4.accept(this, argu);

      if (_simpleExp.startsWith("TEMP ")) {
          currDataSets.use.add(_simpleExp);
      }
      return _ret;
   }

   /**
    * f0 -> "HALLOCATE"
    * f1 -> SimpleExp()
    */
   public R visit(HAllocate n, A argu) {
      InstrNode currDataSets = dataSets.get(instr);

      R _ret=null;
      n.f0.accept(this, argu);
      String _simpleExp = (String)n.f1.accept(this, argu);

      if (_simpleExp.startsWith("TEMP ")) {
          currDataSets.use.add(_simpleExp);
      }
      return _ret;
   }

   /**
    * f0 -> Operator()
    * f1 -> Temp()
    * f2 -> SimpleExp()
    */
   public R visit(BinOp n, A argu) {
      InstrNode currDataSets = dataSets.get(instr);

      R _ret=null;
      n.f0.accept(this, argu);
      String t1 = (String)n.f1.accept(this, argu);
      String _simpleExp = (String)n.f2.accept(this, argu);

      currDataSets.use.add(t1);
      if (_simpleExp.startsWith("TEMP ")) {
          currDataSets.use.add(_simpleExp);
      }
      return _ret;
   }

   /**
    * f0 -> "LE"
    *       | "NE"
    *       | "PLUS"
    *       | "MINUS"
    *       | "TIMES"
    *       | "DIV"
    */
   public R visit(Operator n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Temp()
    *       | IntegerLiteral()
    *       | Label()
    */
   public R visit(SimpleExp n, A argu) {
      R _ret = n.f0.accept(this, argu);

      if (moveFlag) {
          InstrNode currDataSets = dataSets.get(instr);
          String str = (String)_ret;
          if (str.startsWith("TEMP ")) {
              currDataSets.use.add(str);
          }
      }
      return _ret;
   }

   /**
    * f0 -> "TEMP"
    * f1 -> IntegerLiteral()
    */
   public R visit(Temp n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String intLiteral = (String)n.f1.accept(this, argu);
      _ret = (R)("TEMP " + intLiteral);

      if (callFlag) {
          InstrNode currDataSets = dataSets.get(instr);
          currDataSets.use.add((String)_ret);
      }
      return _ret;
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public R visit(IntegerLiteral n, A argu) {
      R _ret = (R)n.f0.toString();
      return _ret;
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(Label n, A argu) {
      R _ret = (R)n.f0.toString();
      return _ret;
   }

}
