//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class Pass1<R,A> implements GJVisitor<R,A> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //

   ArrayList<InstrNode> dataSets = new ArrayList<>(); // stores use and def sets of each instruction
   int instr = 0; // index of an instruction (i.e., instructions are numbered from 0)

   String scope = new String();
   HashMap<String, HashMap<String, Integer>> labelIdx = new HashMap<>(); // scope -> label -> index
   HashMap<String, Integer> currScopeLabelIdx = new HashMap<>();         // label -> instruction index in the current scope
   boolean moveFlag = false;
   boolean callFlag = false;

   ArrayList<Integer> roots = new ArrayList<>();
   ArrayList<String> scopeList = new ArrayList<>();

   HashSet<String> temporaries = new HashSet<>();     // stores all the temporaries used in the program
   public HashMap<String, HashMap<String, LiveRange>> liveRange = new HashMap<>(); // scope -> temp -> live range
   
   // for debugging
   void print_liveRange() {
       for (String _scope : scopeList) {
           System.out.println(_scope);
           for (Map.Entry<String, LiveRange> entry : liveRange.get(_scope).entrySet()) {
               String _temp = entry.getKey();
               LiveRange _range = entry.getValue();
               System.out.println(_temp + " -> " + _range.min + ", " + _range.max);
           }
           System.out.println();
       }
   }

   public R visit(NodeList n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeListOptional n, A argu) {
      if ( n.present() ) {
         R _ret=null;
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
            _count++;
         }
         return _ret;
      }
      else
         return null;
   }

   public R visit(NodeOptional n, A argu) { // the node in the NodeOptional can only be label according to the grammar
      if ( n.present() ) {
         String _label = (String)n.node.accept(this,argu);
         currScopeLabelIdx.put(_label, instr);
      }
      return null;
   }

   public R visit(NodeSequence n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeToken n, A argu) { return null; }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> "MAIN"
    * f1 -> StmtList()
    * f2 -> "END"
    * f3 -> ( Procedure() )*
    * f4 -> <EOF>
    */
   public R visit(Goal n, A argu) {
      scope = "MAIN";
      roots.add(instr);
      scopeList.add(scope);
      
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      
      labelIdx.put(scope, currScopeLabelIdx);
      currScopeLabelIdx = new HashMap<>();
      scope = new String();

      n.f3.accept(this, argu);
      n.f4.accept(this, argu);

      // computes in and out sets for each instruction
      for (int i = 0; i < roots.size(); ++i) {
          int _start = roots.get(i);
          int _end;
          if (i + 1 < roots.size()) {
              _end = roots.get(i + 1);
          }
          else {
              _end = instr;
          }
          String currScope = scopeList.get(i);

          boolean change;
          do {
              change = false;
              for (int j = _start; j < _end; ++j) {
                  InstrNode currNode = dataSets.get(j);
                  HashSet<String> old_in = new HashSet<>(currNode.in);
                  HashSet<String> old_out = new HashSet<>(currNode.out);

                  HashSet<String> new_in = new HashSet<>(currNode.out);
                  new_in.removeAll(currNode.def);
                  new_in.addAll(currNode.use);
                  if (!new_in.equals(old_in)) {
                      change = true;
                      currNode.in = new_in;
                  }

                  HashSet<String> new_out = new HashSet<>();
                  if (j + 1 < _end) {
                      InstrNode nextNode = dataSets.get(j + 1);
                      new_out.addAll(nextNode.in);
                  }
                  if (currNode.targetLabel != null) {
                      InstrNode nextNode = dataSets.get(labelIdx.get(currScope).get(currNode.targetLabel));
                      new_out.addAll(nextNode.in);
                  }
                  if (!new_out.equals(old_out)) {
                      change = true;
                      currNode.out = new_out;
                  }
              }
          } while (change);
      }

      // computes the live range for each temp
      for (int i = 0; i < roots.size(); ++i) {
          int _start = roots.get(i);
          int _end = (i + 1 < roots.size()) ? roots.get(i + 1) : instr;
          String currScope = scopeList.get(i);
          HashMap<String, LiveRange> currLiveRange = new HashMap<>();

          for (int j = _start; j < _end; ++j) {
              InstrNode currNode = dataSets.get(j);
              for (String _temp : currNode.in) {
                  if (!currLiveRange.containsKey(_temp)) {
                      LiveRange _obj = new LiveRange();
                      _obj.min = j;
                      currLiveRange.put(_temp, _obj);
                  }
                  int old_max = currLiveRange.get(_temp).max;
                  currLiveRange.get(_temp).max = (j > old_max) ? j : old_max;
              }
          }

          liveRange.put(currScope, currLiveRange);
      }
      return _ret;
   }

   /**
    * f0 -> ( ( Label() )? Stmt() )*
    */
   public R visit(StmtList n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Label()
    * f1 -> "["
    * f2 -> IntegerLiteral()
    * f3 -> "]"
    * f4 -> StmtExp()
    */
   public R visit(Procedure n, A argu) {
      roots.add(instr);

      R _ret=null;
      scope = (String)n.f0.accept(this, argu);
      scopeList.add(scope);

      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);

      labelIdx.put(scope, currScopeLabelIdx);
      currScopeLabelIdx = new HashMap<>();
      scope = new String();
      return _ret;
   }

   /**
    * f0 -> NoOpStmt()
    *       | ErrorStmt()
    *       | CJumpStmt()
    *       | JumpStmt()
    *       | HStoreStmt()
    *       | HLoadStmt()
    *       | MoveStmt()
    *       | PrintStmt()
    */
   public R visit(Stmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);

      ++instr;
      return _ret;
   }

   /**
    * f0 -> "NOOP"
    */
   public R visit(NoOpStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);

      dataSets.add(new InstrNode());
      return _ret;
   }

   /**
    * f0 -> "ERROR"
    */
   public R visit(ErrorStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);

      dataSets.add(new InstrNode());
      return _ret;
   }

   /**
    * f0 -> "CJUMP"
    * f1 -> Temp()
    * f2 -> Label()
    */
   public R visit(CJumpStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String t = (String)n.f1.accept(this, argu);
      String _label = (String)n.f2.accept(this, argu);

      InstrNode currDataSets = new InstrNode();
      currDataSets.use.add(t);
      currDataSets.targetLabel = _label;
      dataSets.add(currDataSets);
      return _ret;
   }

   /**
    * f0 -> "JUMP"
    * f1 -> Label()
    */
   public R visit(JumpStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String _label = (String)n.f1.accept(this, argu);

      InstrNode currDataSets = new InstrNode();
      currDataSets.targetLabel = _label; 
      dataSets.add(currDataSets);
      return _ret;
   }

   /**
    * f0 -> "HSTORE"
    * f1 -> Temp()
    * f2 -> IntegerLiteral()
    * f3 -> Temp()
    */
   public R visit(HStoreStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String t1 = (String)n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      String t2 = (String)n.f3.accept(this, argu);

      InstrNode currDataSets = new InstrNode();
      currDataSets.use.add(t1);
      currDataSets.use.add(t2);
      dataSets.add(currDataSets);
      return _ret;
   }

   /**
    * f0 -> "HLOAD"
    * f1 -> Temp()
    * f2 -> Temp()
    * f3 -> IntegerLiteral()
    */
   public R visit(HLoadStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String t1 = (String)n.f1.accept(this, argu);
      String t2 = (String)n.f2.accept(this, argu);
      n.f3.accept(this, argu);

      InstrNode currDataSets = new InstrNode();
      currDataSets.def.add(t1);
      currDataSets.use.add(t2);
      dataSets.add(currDataSets);
      return _ret;
   }

   /**
    * f0 -> "MOVE"
    * f1 -> Temp()
    * f2 -> Exp()
    */
   public R visit(MoveStmt n, A argu) {
      InstrNode currDataSets = new InstrNode();
      dataSets.add(currDataSets);

      R _ret=null;
      n.f0.accept(this, argu);
      String t1 = (String)n.f1.accept(this, argu);

      moveFlag = true;
      n.f2.accept(this, argu);
      moveFlag = false;

      currDataSets.def.add(t1);
      return _ret;
   }

   /**
    * f0 -> "PRINT"
    * f1 -> SimpleExp()
    */
   public R visit(PrintStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String _simpleExp = (String)n.f1.accept(this, argu);

      InstrNode currDataSets = new InstrNode();
      if (_simpleExp.startsWith("TEMP ")) {
          currDataSets.use.add(_simpleExp);
      }
      dataSets.add(currDataSets);
      return _ret;
   }

   /**
    * f0 -> Call()
    *       | HAllocate()
    *       | BinOp()
    *       | SimpleExp()
    */
   public R visit(Exp n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "BEGIN"
    * f1 -> StmtList()
    * f2 -> "RETURN"
    * f3 -> SimpleExp()
    * f4 -> "END"
    */
   public R visit(StmtExp n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      String _simpleExp = (String)n.f3.accept(this, argu);
      n.f4.accept(this, argu);

      InstrNode currDataSets = new InstrNode();
      if (_simpleExp.startsWith("TEMP ")) {
          currDataSets.use.add(_simpleExp);
      }
      dataSets.add(currDataSets);
      ++instr;
      return _ret;
   }

   /**
    * f0 -> "CALL"
    * f1 -> SimpleExp()
    * f2 -> "("
    * f3 -> ( Temp() )*
    * f4 -> ")"
    */
   public R visit(Call n, A argu) {
      InstrNode currDataSets = dataSets.get(instr);

      R _ret=null;
      n.f0.accept(this, argu);
      String _simpleExp = (String)n.f1.accept(this, argu);
      n.f2.accept(this, argu);

      callFlag = true;
      n.f3.accept(this, argu);
      callFlag = false;

      n.f4.accept(this, argu);

      if (_simpleExp.startsWith("TEMP ")) {
          currDataSets.use.add(_simpleExp);
      }
      return _ret;
   }

   /**
    * f0 -> "HALLOCATE"
    * f1 -> SimpleExp()
    */
   public R visit(HAllocate n, A argu) {
      InstrNode currDataSets = dataSets.get(instr);

      R _ret=null;
      n.f0.accept(this, argu);
      String _simpleExp = (String)n.f1.accept(this, argu);

      if (_simpleExp.startsWith("TEMP ")) {
          currDataSets.use.add(_simpleExp);
      }
      return _ret;
   }

   /**
    * f0 -> Operator()
    * f1 -> Temp()
    * f2 -> SimpleExp()
    */
   public R visit(BinOp n, A argu) {
      InstrNode currDataSets = dataSets.get(instr);

      R _ret=null;
      n.f0.accept(this, argu);
      String t1 = (String)n.f1.accept(this, argu);
      String _simpleExp = (String)n.f2.accept(this, argu);

      currDataSets.use.add(t1);
      if (_simpleExp.startsWith("TEMP ")) {
          currDataSets.use.add(_simpleExp);
      }
      return _ret;
   }

   /**
    * f0 -> "LE"
    *       | "NE"
    *       | "PLUS"
    *       | "MINUS"
    *       | "TIMES"
    *       | "DIV"
    */
   public R visit(Operator n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Temp()
    *       | IntegerLiteral()
    *       | Label()
    */
   public R visit(SimpleExp n, A argu) {
      R _ret = n.f0.accept(this, argu);

      if (moveFlag) {
          InstrNode currDataSets = dataSets.get(instr);
          String str = (String)_ret;
          if (str.startsWith("TEMP ")) {
              currDataSets.use.add(str);
          }
      }
      return _ret;
   }

   /**
    * f0 -> "TEMP"
    * f1 -> IntegerLiteral()
    */
   public R visit(Temp n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String intLiteral = (String)n.f1.accept(this, argu);
      _ret = (R)("TEMP " + intLiteral);

      if (callFlag) {
          InstrNode currDataSets = dataSets.get(instr);
          currDataSets.use.add((String)_ret);
      }
      temporaries.add((String)_ret);
      return _ret;
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public R visit(IntegerLiteral n, A argu) {
      R _ret = (R)n.f0.toString();
      return _ret;
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(Label n, A argu) {
      R _ret = (R)n.f0.toString();
      return _ret;
   }

}
