//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class GJDepthFirstPass2<R,A> implements GJVisitor<R,A> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   
   public HashMap<String, CustomType> symbolTable = new HashMap<String, CustomType>(); // Identifier -> Class
   
   CustomType currClass = null;
   Method currMethod = null;
   int varFlag = 0; // 1. PrimaryExpression sets it to 1 at the beginning and then resets to 0 before returing.
                    // 2. If it is 1, then Identifier sets it to 2
   Stack<ArrayList<String>> argStack = new Stack<ArrayList<String>>();
   boolean isAllocation = false;

   void typeError() {
       System.out.println("Type error");
       System.exit(1);
   }

   void symbolNotFound() {
       System.out.println("Symbol not found");
       System.exit(1);
   }

   boolean isValidCustomType(String _type) {
       if (_type == null) {
           return false;
       }
       return symbolTable.containsKey(_type);
   }

   String getInstanceVarType(String variable) {
       String _type = currClass.name;
       while (_type != null && isValidCustomType(_type)) {
           CustomType _currClass = symbolTable.get(_type);
           if (_currClass.instanceVar.containsKey(variable)) {
               return _currClass.instanceVar.get(variable);
           }
           _type = _currClass.parent;
       }
       symbolNotFound();
       return null;
   }

   String getIdentifierType(String variable) {
       if (currMethod != null) {
           if (currMethod.localVar.containsKey(variable)) {
               return currMethod.localVar.get(variable);
           }
           else if (currMethod.paramType.containsKey(variable)){
               return currMethod.paramType.get(variable);
           }
           else {
               return getInstanceVarType(variable);
           }
       }
       else {
           return getInstanceVarType(variable);
       }
   }

   boolean isAssignable(String lhs, String rhs) {
       if (lhs.equals(rhs)) {
           return true;
       }
       else if (isValidCustomType(lhs)) {
           while (rhs != null && isValidCustomType(rhs)) {
               if (rhs.equals(lhs)) {
                   return true;
               }
               CustomType _currClass = symbolTable.get(rhs);
               rhs = _currClass.parent;
           }
           return false;
       }
       else {
           return false;
       }
   }

   boolean areCompatible(String _type1, String _type2) {
       return isAssignable(_type1, _type2) || isAssignable(_type2, _type1);
   }

   Method getMethod(String _type, String _methodName) {
       while (_type != null && isValidCustomType(_type)) {
           CustomType _currClass = symbolTable.get(_type);
           if (_currClass.method.containsKey(_methodName)) {
               return _currClass.method.get(_methodName);
           }
           _type = _currClass.parent;
       }
       symbolNotFound();
       return null;
   }

   void validateArgs(Method _method, ArrayList<String> _argList) {
       ArrayList _paramList = _method.paramList;
       if (_paramList == null && _argList == null) {
           return;
       }
       else if (_paramList == null || _argList == null) {
           typeError();
       }
       else {
           if (_paramList.size() != _argList.size()) {
               typeError();
           }
           for (int i = 0; i < _paramList.size(); i++) {
               String _lhs = _method.paramType.get(_paramList.get(i));
               String _rhs = _argList.get(i);
               if (!isAssignable(_lhs, _rhs)) {
                   typeError();
               }
           }
       }
   }

   public R visit(NodeList n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeListOptional n, A argu) {
      if ( n.present() ) {
         R _ret=null;
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
            _count++;
         }
         return _ret;
      }
      else
         return null;
   }

   public R visit(NodeOptional n, A argu) {
      if ( n.present() )
         return n.node.accept(this,argu);
      else
         return null;
   }

   public R visit(NodeSequence n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeToken n, A argu) { return null; }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> ( ImportFunction() )?
    * f1 -> MainClass()
    * f2 -> ( TypeDeclaration() )*
    * f3 -> <EOF>
    */
   public R visit(Goal n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "import"
    * f1 -> "java.util.function.Function"
    * f2 -> ";"
    */
   public R visit(ImportFunction n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> "public"
    * f4 -> "static"
    * f5 -> "void"
    * f6 -> "main"
    * f7 -> "("
    * f8 -> "String"
    * f9 -> "["
    * f10 -> "]"
    * f11 -> Identifier()
    * f12 -> ")"
    * f13 -> "{"
    * f14 -> PrintStatement()
    * f15 -> "}"
    * f16 -> "}"
    */
   public R visit(MainClass n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      n.f7.accept(this, argu);
      n.f8.accept(this, argu);
      n.f9.accept(this, argu);
      n.f10.accept(this, argu);
      n.f11.accept(this, argu);
      n.f12.accept(this, argu);
      n.f13.accept(this, argu);
      n.f14.accept(this, argu);
      n.f15.accept(this, argu);
      n.f16.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ClassDeclaration()
    *       | ClassExtendsDeclaration()
    */
   public R visit(TypeDeclaration n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> ( VarDeclaration() )*
    * f4 -> ( MethodDeclaration() )*
    * f5 -> "}"
    */
   public R visit(ClassDeclaration n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String className = (String)n.f1.accept(this, argu);
      currClass = symbolTable.get(className);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      currClass = null;
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "extends"
    * f3 -> Identifier()
    * f4 -> "{"
    * f5 -> ( VarDeclaration() )*
    * f6 -> ( MethodDeclaration() )*
    * f7 -> "}"
    */
   public R visit(ClassExtendsDeclaration n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String className = (String)n.f1.accept(this, argu);
      currClass = symbolTable.get(className);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      n.f7.accept(this, argu);
      currClass = null;
      return _ret;
   }

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    * f2 -> ";"
    */
   public R visit(VarDeclaration n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "public"
    * f1 -> Type()
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( FormalParameterList() )?
    * f5 -> ")"
    * f6 -> "{"
    * f7 -> ( VarDeclaration() )*
    * f8 -> ( Statement() )*
    * f9 -> "return"
    * f10 -> Expression()
    * f11 -> ";"
    * f12 -> "}"
    */
   public R visit(MethodDeclaration n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String methodName = (String)n.f2.accept(this, argu);
      currMethod = currClass.method.get(methodName);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      n.f7.accept(this, argu);
      n.f8.accept(this, argu);
      n.f9.accept(this, argu);
      n.f10.accept(this, argu);
      n.f11.accept(this, argu);
      n.f12.accept(this, argu);
      currMethod = null;
      return _ret;
   }

   /**
    * f0 -> FormalParameter()
    * f1 -> ( FormalParameterRest() )*
    */
   public R visit(FormalParameterList n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    */
   public R visit(FormalParameter n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ","
    * f1 -> FormalParameter()
    */
   public R visit(FormalParameterRest n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ArrayType()
    *       | BooleanType()
    *       | IntegerType()
    *       | Identifier()
    *       | LambdaType()
    */
   public R visit(Type n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "int"
    * f1 -> "["
    * f2 -> "]"
    */
   public R visit(ArrayType n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "boolean"
    */
   public R visit(BooleanType n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "int"
    */
   public R visit(IntegerType n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "Function"
    * f1 -> "<"
    * f2 -> Identifier()
    * f3 -> ","
    * f4 -> Identifier()
    * f5 -> ">"
    */
   public R visit(LambdaType n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Block()
    *       | AssignmentStatement()
    *       | ArrayAssignmentStatement()
    *       | IfStatement()
    *       | WhileStatement()
    *       | PrintStatement()
    */
   public R visit(Statement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "{"
    * f1 -> ( Statement() )*
    * f2 -> "}"
    */
   public R visit(Block n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> "="
    * f2 -> Expression()
    * f3 -> ";"
    */
   public R visit(AssignmentStatement n, A argu) {
      R _ret=null;
      String variable = (String)n.f0.accept(this, argu);
      String lhsType = getIdentifierType(variable);
      n.f1.accept(this, argu);
      String rhsType = (String)n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      if (!isAssignable(lhsType, rhsType)) {
          typeError();
      }
      return _ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> "["
    * f2 -> Expression()
    * f3 -> "]"
    * f4 -> "="
    * f5 -> Expression()
    * f6 -> ";"
    */
   public R visit(ArrayAssignmentStatement n, A argu) {
      R _ret=null;
      String variable = (String)n.f0.accept(this, argu);
      String varType = getIdentifierType(variable);
      if (!varType.equals("int[]")) {
          typeError();
      }
      n.f1.accept(this, argu);
      String index = (String)n.f2.accept(this, argu);
      if (!index.equals("int")) {
          typeError();
      }
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      String rhsType = (String)n.f5.accept(this, argu);
      if (!rhsType.equals("int")) {
          typeError();
      }
      n.f6.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> IfthenElseStatement()
    *       | IfthenStatement()
    */
   public R visit(IfStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "if"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public R visit(IfthenStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String conditionType = (String)n.f2.accept(this, argu);
      if (!conditionType.equals("boolean")) {
          typeError();
      }
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "if"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    * f5 -> "else"
    * f6 -> Statement()
    */
   public R visit(IfthenElseStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String conditionType = (String)n.f2.accept(this, argu);
      if (!conditionType.equals("boolean")) {
          typeError();
      }
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "while"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public R visit(WhileStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String conditionType = (String)n.f2.accept(this, argu);
      if (!conditionType.equals("boolean")) {
          typeError();
      }
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "System.out.println"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> ";"
    */
   public R visit(PrintStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String expType = (String)n.f2.accept(this, argu);
      if (!expType.equals("int")) {
          typeError();
      }
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> OrExpression()
    *       | AndExpression()
    *       | CompareExpression()
    *       | neqExpression()
    *       | AddExpression()
    *       | MinusExpression()
    *       | TimesExpression()
    *       | DivExpression()
    *       | ArrayLookup()
    *       | ArrayLength()
    *       | MessageSend()
    *       | LambdaExpression()
    *       | PrimaryExpression()
    */
   public R visit(Expression n, A argu) {
      R _ret = n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "("
    * f1 -> Identifier()
    * f2 -> ")"
    * f3 -> "->"
    * f4 -> Expression()
    */
   public R visit(LambdaExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "&&"
    * f2 -> PrimaryExpression()
    */
   public R visit(AndExpression n, A argu) {
      String _ret = "boolean";
      String type1 = (String)n.f0.accept(this, argu);
      if (!type1.equals("boolean")) {
          typeError();
      }
      n.f1.accept(this, argu);
      String type2 = (String)n.f2.accept(this, argu);
      if (!type2.equals("boolean")) {
          typeError();
      }
      return (R)_ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "||"
    * f2 -> PrimaryExpression()
    */
   public R visit(OrExpression n, A argu) {
      String _ret = "boolean";
      String type1 = (String)n.f0.accept(this, argu);
      if (!type1.equals("boolean")) {
          typeError();
      }
      n.f1.accept(this, argu);
      String type2 = (String)n.f2.accept(this, argu);
      if (!type2.equals("boolean")) {
          typeError();
      }
      return (R)_ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "<="
    * f2 -> PrimaryExpression()
    */
   public R visit(CompareExpression n, A argu) {
      String _ret = "boolean";
      String type1 = (String)n.f0.accept(this, argu);
      if (!type1.equals("int")) {
          typeError();
      }
      n.f1.accept(this, argu);
      String type2 = (String)n.f2.accept(this, argu);
      if (!type2.equals("int")) {
          typeError();
      }
      return (R)_ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "!="
    * f2 -> PrimaryExpression()
    */
   public R visit(neqExpression n, A argu) {
      String _ret = "boolean";
      String type1 = (String)n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String type2 = (String)n.f2.accept(this, argu);
      if (!type1.equals(type2) && !(isValidCustomType(type1) && isValidCustomType(type2) && areCompatible(type1, type2))) {
          typeError();
      }
      return (R)_ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "+"
    * f2 -> PrimaryExpression()
    */
   public R visit(AddExpression n, A argu) {
      String _ret = "int";
      String type1 = (String)n.f0.accept(this, argu);
      if (!type1.equals("int")) {
          typeError();
      }
      n.f1.accept(this, argu);
      String type2 = (String)n.f2.accept(this, argu);
      if (!type2.equals("int")) {
          typeError();
      }
      return (R)_ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "-"
    * f2 -> PrimaryExpression()
    */
   public R visit(MinusExpression n, A argu) {
      String _ret = "int";
      String type1 = (String)n.f0.accept(this, argu);
      if (!type1.equals("int")) {
          typeError();
      }
      n.f1.accept(this, argu);
      String type2 = (String)n.f2.accept(this, argu);
      if (!type2.equals("int")) {
          typeError();
      }
      return (R)_ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "*"
    * f2 -> PrimaryExpression()
    */
   public R visit(TimesExpression n, A argu) {
      String _ret = "int";
      String type1 = (String)n.f0.accept(this, argu);
      if (!type1.equals("int")) {
          typeError();
      }
      n.f1.accept(this, argu);
      String type2 = (String)n.f2.accept(this, argu);
      if (!type2.equals("int")) {
          typeError();
      }
      return (R)_ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "/"
    * f2 -> PrimaryExpression()
    */
   public R visit(DivExpression n, A argu) {
      String _ret = "int";
      String type1 = (String)n.f0.accept(this, argu);
      if (!type1.equals("int")) {
          typeError();
      }
      n.f1.accept(this, argu);
      String type2 = (String)n.f2.accept(this, argu);
      if (!type2.equals("int")) {
          typeError();
      }
      return (R)_ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "["
    * f2 -> PrimaryExpression()
    * f3 -> "]"
    */
   public R visit(ArrayLookup n, A argu) {
      String _ret = "int";
      String type1 = (String)n.f0.accept(this, argu);
      if (!type1.equals("int[]")) {
          typeError();
      }
      n.f1.accept(this, argu);
      String type2 = (String)n.f2.accept(this, argu);
      if (!type2.equals("int")) {
          typeError();
      }
      n.f3.accept(this, argu);
      return (R)_ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "."
    * f2 -> "length"
    */
   public R visit(ArrayLength n, A argu) {
      String _ret = "int";
      String _type = (String)n.f0.accept(this, argu);
      if (!_type.equals("int[]")) {
          typeError();
      }
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return (R)_ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "."
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( ExpressionList() )?
    * f5 -> ")"
    */
   public R visit(MessageSend n, A argu) { // Take care of lambda
      String _ret = new String();
      String _type = (String)n.f0.accept(this, argu);
      argStack.push(new ArrayList<String>());
      n.f1.accept(this, argu);
      String _methodName = (String)n.f2.accept(this, argu);
      Method _method = getMethod(_type, _methodName);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      if (!argStack.isEmpty()) {
          validateArgs(_method, argStack.peek());
      }
      else {
          validateArgs(_method, null);
      }
      argStack.pop();
      _ret = _method.returnType;
      return (R)_ret;
   }

   /**
    * f0 -> Expression()
    * f1 -> ( ExpressionRest() )*
    */
   public R visit(ExpressionList n, A argu) {
      R _ret=null;
      String _argType = (String)n.f0.accept(this, argu);
      argStack.peek().add(_argType);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ","
    * f1 -> Expression()
    */
   public R visit(ExpressionRest n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String _argType = (String)n.f1.accept(this, argu);
      argStack.peek().add(_argType);
      return _ret;
   }

   /**
    * f0 -> IntegerLiteral()
    *       | TrueLiteral()
    *       | FalseLiteral()
    *       | Identifier()
    *       | ThisExpression()
    *       | ArrayAllocationExpression()
    *       | AllocationExpression()
    *       | NotExpression()
    *       | BracketExpression()
    */
   public R visit(PrimaryExpression n, A argu) {
      varFlag = 1;
      R _ret = n.f0.accept(this, argu);
      if (varFlag == 2) { // have to return the type of the identifier (which is variable in this case)
          _ret = (R)getIdentifierType((String)_ret);
      }
      varFlag = 0;
      return _ret;
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public R visit(IntegerLiteral n, A argu) {
      String _ret = "int";
      n.f0.accept(this, argu);
      return (R)_ret;
   }

   /**
    * f0 -> "true"
    */
   public R visit(TrueLiteral n, A argu) {
      String _ret = "boolean";
      n.f0.accept(this, argu);
      return (R)_ret;
   }

   /**
    * f0 -> "false"
    */
   public R visit(FalseLiteral n, A argu) {
      String _ret = "boolean";
      n.f0.accept(this, argu);
      return (R)_ret;
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(Identifier n, A argu) {
      if (varFlag == 1 && !isAllocation) {
          varFlag = 2;
      }
      String _ret = n.f0.toString();
      return (R)_ret;
   }

   /**
    * f0 -> "this"
    */
   public R visit(ThisExpression n, A argu) {
      n.f0.accept(this, argu);
      String _ret = currClass.name;
      return (R)_ret;
   }

   /**
    * f0 -> "new"
    * f1 -> "int"
    * f2 -> "["
    * f3 -> Expression()
    * f4 -> "]"
    */
   public R visit(ArrayAllocationExpression n, A argu) {
      String _ret = "int[]";
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      String expType = (String)n.f3.accept(this, argu);
      if (!expType.equals("int")) {
          typeError();
      }
      n.f4.accept(this, argu);
      return (R)_ret;
   }

   /**
    * f0 -> "new"
    * f1 -> Identifier()
    * f2 -> "("
    * f3 -> ")"
    */
   public R visit(AllocationExpression n, A argu) {
      isAllocation = true;
      n.f0.accept(this, argu);
      String _ret = (String)n.f1.accept(this, argu);
      if (!isValidCustomType(_ret)) {
          typeError();
      }
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      isAllocation = false;
      return (R)_ret;
   }

   /**
    * f0 -> "!"
    * f1 -> Expression()
    */
   public R visit(NotExpression n, A argu) {
      n.f0.accept(this, argu);
      String _ret = (String)n.f1.accept(this, argu);
      if (!_ret.equals("boolean")) {
          typeError();
      }
      return (R)_ret;
   }

   /**
    * f0 -> "("
    * f1 -> Expression()
    * f2 -> ")"
    */
   public R visit(BracketExpression n, A argu) {
      n.f0.accept(this, argu);
      String _ret = (String)n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return (R)_ret;
   }

}
