//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class Pass1<R,A> implements GJVisitor<R,A> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //

   class Return {
       Return() {
           code = new String();
           ret = new String();
           argList = new String();
       }
       String code;
       String ret;
       String argList;
   }

   int tempCounter = 10000;
   String genTemp() {
       --tempCounter;
       return "TEMP " + tempCounter;
   }

   HashMap<String, String> tempMap = new HashMap<>(); // temporary to temporary
   String argStr = new String();

   boolean flag = false;  // flag for HSTORE
   boolean flag2 = false; // flag for Operator

   public R visit(NodeList n, A argu) {
      Return r = new Return();

      R _ret = (R)r;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeListOptional n, A argu) {
      Return r = new Return();

      R _ret = (R)r;
      if ( n.present() ) {
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            Return obj = (Return)e.nextElement().accept(this,argu);
            r.code += obj.code;
            if (obj.ret.startsWith("TEMP")) {
                r.argList += obj.ret + " ";
            }
            else if (!obj.ret.equals("")) {
                String _temp = genTemp();
                argStr += "MOVE " + _temp + " " + obj.ret + "\n";
                r.argList += _temp + " ";
            }
            _count++;
         }
      }
      return _ret;
   }

   public R visit(NodeOptional n, A argu) {
      Return r = new Return();

      if ( n.present() ) {
         r = (Return)n.node.accept(this,argu);
         r.code = r.ret + "\n";
         r.ret = "";
      }
      return (R)r;
   }

   public R visit(NodeSequence n, A argu) {
      Return r = new Return();

      R _ret = (R)r;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         Return obj = (Return)e.nextElement().accept(this,argu);
         r.code += obj.code;
         _count++;
      }
      return _ret;
   }

   public R visit(NodeToken n, A argu) { 
       Return r = new Return();
       return (R)r;
   }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> "MAIN"
    * f1 -> StmtList()
    * f2 -> "END"
    * f3 -> ( Procedure() )*
    * f4 -> <EOF>
    */
   public R visit(Goal n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      Return o1 = (Return)n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      Return o2 = (Return)n.f3.accept(this, argu);
      n.f4.accept(this, argu);

      System.out.println("MAIN");
      System.out.print(o1.code);
      System.out.println("END\n");
      System.out.println(o2.code);
      return _ret;
   }

   /**
    * f0 -> ( ( Label() )? Stmt() )*
    */
   public R visit(StmtList n, A argu) {
      R _ret = n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Label()
    * f1 -> "["
    * f2 -> IntegerLiteral()
    * f3 -> "]"
    * f4 -> StmtExp()
    */
   public R visit(Procedure n, A argu) {
      Return r = new Return();

      R _ret = (R)r;
      Return o1 = (Return)n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      Return o2 = (Return)n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      Return o3 = (Return)n.f4.accept(this, argu);

      r.code = o1.ret + " [" + o2.ret + "] BEGIN\n" + o3.code + "END\n";
      return _ret;
   }

   /**
    * f0 -> NoOpStmt()
    *       | ErrorStmt()
    *       | CJumpStmt()
    *       | JumpStmt()
    *       | HStoreStmt()
    *       | HLoadStmt()
    *       | MoveStmt()
    *       | PrintStmt()
    */
   public R visit(Stmt n, A argu) {
      R _ret = n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "NOOP"
    */
   public R visit(NoOpStmt n, A argu) {
      Return r = new Return();

      R _ret = (R)r;
      n.f0.accept(this, argu);
      r.code = "NOOP\n";
      return _ret;
   }

   /**
    * f0 -> "ERROR"
    */
   public R visit(ErrorStmt n, A argu) {
      Return r = new Return();

      R _ret = (R)r;
      n.f0.accept(this, argu);
      r.code = "ERROR\n";
      return _ret;
   }

   /**
    * f0 -> "CJUMP"
    * f1 -> Exp()
    * f2 -> Label()
    */
   public R visit(CJumpStmt n, A argu) {
      Return r = new Return();
      Return s = new Return();

      R _ret = (R)r;
      n.f0.accept(this, argu);
      Return o1 = (Return)n.f1.accept(this, (A)s);
      Return o2 = (Return)n.f2.accept(this, argu);
      r.code = s.code + "CJUMP " + o1.ret + " " + o2.ret + "\n";
      return _ret;
   }

   /**
    * f0 -> "JUMP"
    * f1 -> Label()
    */
   public R visit(JumpStmt n, A argu) {
      Return r = new Return();

      R _ret = (R)r;
      n.f0.accept(this, argu);
      Return obj = (Return)n.f1.accept(this, argu);
      r.code = "JUMP " + obj.ret + "\n";
      return _ret;
   }

   /**
    * f0 -> "HSTORE"
    * f1 -> Exp()
    * f2 -> IntegerLiteral()
    * f3 -> Exp()
    */
   public R visit(HStoreStmt n, A argu) {
      Return r = new Return();
      Return s1 = new Return();
      Return s2 = new Return();

      R _ret = (R)r;
      n.f0.accept(this, argu);
      Return o1 = (Return)n.f1.accept(this, (A)s1);
      Return o2 = (Return)n.f2.accept(this, argu);
      flag = false;
      Return o3 = (Return)n.f3.accept(this, (A)s2);

      if (flag) {
          String t = genTemp();
          r.code += s1.code + s2.code + "MOVE " + t + " " + o3.ret + "\n";
          r.code += "HSTORE " + o1.ret + " " + o2.ret + " " + t + "\n";
          flag = false;
      }
      else {
          r.code = s1.code + s2.code + "HSTORE " + o1.ret + " " + o2.ret + " " + o3.ret + "\n";
      }
      return _ret;
   }

   /**
    * f0 -> "HLOAD"
    * f1 -> Temp()
    * f2 -> Exp()
    * f3 -> IntegerLiteral()
    */
   public R visit(HLoadStmt n, A argu) {
      Return r = new Return();
      Return s = new Return();

      R _ret = (R)r;
      n.f0.accept(this, argu);
      Return o1 = (Return)n.f1.accept(this, argu);
      Return o2 = (Return)n.f2.accept(this, (A)s);
      Return o3 = (Return)n.f3.accept(this, argu);
      r.code = s.code + "HLOAD " + o1.ret + " " + o2.ret + " " + o3.ret + "\n";
      return _ret;
   }

   /**
    * f0 -> "MOVE"
    * f1 -> Temp()
    * f2 -> Exp()
    */
   public R visit(MoveStmt n, A argu) {
      Return r = new Return();
      Return s = new Return();

      R _ret = (R)r;
      n.f0.accept(this, argu);
      Return o1 = (Return)n.f1.accept(this, argu);
      Return o2 = (Return)n.f2.accept(this, (A)s);
      r.code = s.code + "MOVE " + o1.ret + " " + o2.ret + "\n";
      return _ret;
   }

   /**
    * f0 -> "PRINT"
    * f1 -> Exp()
    */
   public R visit(PrintStmt n, A argu) {
      Return r = new Return();
      Return s = new Return();

      R _ret = (R)r;
      n.f0.accept(this, argu);
      Return obj = (Return)n.f1.accept(this, (A)s);
      r.code = s.code + "PRINT " + obj.ret + "\n";
      return _ret;
   }

   /**
    * f0 -> StmtExp()
    *       | Call()
    *       | HAllocate()
    *       | BinOp()
    *       | Temp()
    *       | IntegerLiteral()
    *       | Label()
    */
   public R visit(Exp n, A argu) {
      R _ret = n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "BEGIN"
    * f1 -> StmtList()
    * f2 -> "RETURN"
    * f3 -> Exp()
    * f4 -> "END"
    */
   public R visit(StmtExp n, A argu) {
      Return r = new Return();
      Return s = new Return();
      Return str = (Return)argu;

      R _ret = (R)r;
      n.f0.accept(this, argu);
      Return o1 = (Return)n.f1.accept(this, argu);
      if (str != null) {
          str.code += o1.code;
      }
      n.f2.accept(this, argu);
      Return o2;
      if (argu == null) {
          o2 = (Return)n.f3.accept(this, (A)s);
      }
      else {
          o2 = (Return)n.f3.accept(this, argu);
      }
      n.f4.accept(this, argu);

      r.code = o1.code + s.code + "RETURN " + o2.ret + "\n";
      r.ret = o2.ret;
      flag = false;
      return _ret;
   }

   /**
    * f0 -> "CALL"
    * f1 -> Exp()
    * f2 -> "("
    * f3 -> ( Exp() )*
    * f4 -> ")"
    */
   public R visit(Call n, A argu) {
      Return r = new Return();
      Return s = (Return)argu;

      R _ret = (R)r;
      n.f0.accept(this, argu);
      Return o1 = (Return)n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      Return o2 = (Return)n.f3.accept(this, argu);
      n.f4.accept(this, argu);

      String t1 = genTemp();

      if (s != null) {
          s.code += argStr; 
          s.code += "MOVE " + t1 + " CALL " + o1.ret + " ( " + o2.argList + ")\n";
      }
      argStr = "";
      r.ret = t1;
      flag = false;
      return _ret;
   }

   /**
    * f0 -> "HALLOCATE"
    * f1 -> Exp()
    */
   public R visit(HAllocate n, A argu) {
      Return r = new Return();
      Return s = (Return)argu;

      R _ret = (R)r;
      n.f0.accept(this, argu);
      Return o1 = (Return)n.f1.accept(this, argu);

      String t1 = genTemp();

      if (s != null) {
          s.code += "MOVE " + t1 + " HALLOCATE " + o1.ret + "\n";
      }
      r.ret = t1;
      flag = false;
      return _ret;
   }

   /**
    * f0 -> Operator()
    * f1 -> Exp()
    * f2 -> Exp()
    */
   public R visit(BinOp n, A argu) {
      Return r = new Return();
      Return s = (Return)argu;

      R _ret = (R)r;
      Return o1 = (Return)n.f0.accept(this, argu);
      flag2 = false;
      Return o2 = (Return)n.f1.accept(this, argu);
      Return o3 = (Return)n.f2.accept(this, argu);

      String t1 = genTemp();

      if (s != null) {
          if (flag2) {
              String t2 = genTemp();
              s.code += "MOVE " + t2 + " " + o2.ret + "\n";
              s.code += "MOVE " + t1 + " " + o1.code + " " + t2 + " " + o3.ret + "\n";
          }
          else {
              s.code += "MOVE " + t1 + " " + o1.code + " " + o2.ret + " " + o3.ret + "\n";
          }
      }
      r.ret = t1;
      flag = false;
      return _ret;
   }

   /**
    * f0 -> "LE"
    *       | "NE"
    *       | "PLUS"
    *       | "MINUS"
    *       | "TIMES"
    *       | "DIV"
    */
   public R visit(Operator n, A argu) {
      Return r = new Return();

      switch(n.f0.which) {
          case 0: r.code = "LE"; break;
          case 1: r.code = "NE"; break;
          case 2: r.code = "PLUS"; break;
          case 3: r.code = "MINUS"; break;
          case 4: r.code = "TIMES"; break;
          case 5: r.code = "DIV"; break;
      }
      R _ret = (R)r;
      return _ret;
   }

   /**
    * f0 -> "TEMP"
    * f1 -> IntegerLiteral()
    */
   public R visit(Temp n, A argu) {
      Return r = new Return();

      R _ret = (R)r;
      n.f0.accept(this, argu);
      Return obj = (Return)n.f1.accept(this, argu);
      /*
      String temp = "TEMP " + obj.ret;
      if (tempMap.containsKey(temp)) {
          r.ret = tempMap.get(temp);
      }
      else {
          r.ret = genTemp();
          tempMap.put(temp, r.ret);
      }
      */
      r.ret = "TEMP " + obj.ret;
      return _ret;
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public R visit(IntegerLiteral n, A argu) {
      Return r = new Return();

      R _ret = (R)r;
      r.ret = n.f0.toString();
      flag = true;
      flag2 = true;
      return _ret;
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(Label n, A argu) {
      Return r = new Return();

      R _ret = (R)r;
      r.ret = n.f0.toString();
      flag = true;
      return _ret;
   }

}
