//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class Pass2<R,A> implements GJVisitor<R,A> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //

   int temporaryCounter = 300; // (If I have time) I have to find the max no.of parameters that a function takes in a program from the first pass
   String genTemp() {
       ++temporaryCounter;
       return "TEMP " + temporaryCounter;
   }

   int labelCounter = 0;
   String genLabel() {
       ++labelCounter;
       return "L" + labelCounter;
   }

   public HashMap<String, CustomType> symbolTable = new HashMap<>();
   public HashMap<String, ClassMemLayout> memLayout = new HashMap<>();

   class Attributes {
       Attributes() {
           type = new String();
           declaredClass = new String();
       }
       String type;
       String declaredClass;
   }

   CustomType currClass = null;
   Method currMethod = null;

   String getInstanceVarType(String variable) {
       if (currClass == null) {
           return "";
       }
       String _type = currClass.name;
       while (_type != null) {
           CustomType _currClass = symbolTable.get(_type);
           if (_currClass.instanceVar.containsKey(variable)) {
               return _currClass.instanceVar.get(variable);
           }
           _type = _currClass.parent;
       }
       return "";
   }

   String getIdentifierType(String variable) {
       if (currMethod != null) {
           if (currMethod.localVar.containsKey(variable)) {
               return currMethod.localVar.get(variable);
           }
           else if (currMethod.paramType.containsKey(variable)){
               return currMethod.paramType.get(variable);
           }
           else {
               return getInstanceVarType(variable);
           }
       }
       else {
           return getInstanceVarType(variable);
       }
   }

   Method getMethod(String _type, String _methodName) {
       while (_type != null) {
           CustomType _currClass = symbolTable.get(_type);
           if (_currClass.method.containsKey(_methodName)) {
               return _currClass.method.get(_methodName);
           }
           _type = _currClass.parent;
       }
       return null;
   }

   boolean isIdentifier(String str) {
       if (str.startsWith("TEMP")) {
           return false;
       }
       char c = str.charAt(0);
       if ('0' <= c && c <= '9') {
           return false;
       }
       return true;
   }

   int parameterIndex = 1;
   boolean paramFlag = false;

   String getDeclClass(String _var) {
       String _type = currClass.name;
       while (_type != null) {
           CustomType _currClass = symbolTable.get(_type);
           if (_currClass.instanceVar.containsKey(_var)) {
               return _type;
           }
           _type = _currClass.parent;
       }
       return "";
   }

   public R visit(NodeList n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeListOptional n, A argu) {
      if ( n.present() ) {
         R _ret=null;
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
            _count++;
         }
         return _ret;
      }
      else
         return null;
   }

   public R visit(NodeOptional n, A argu) {
      if ( n.present() )
         return n.node.accept(this,argu);
      else
         return null;
   }

   public R visit(NodeSequence n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeToken n, A argu) { return null; }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> ( ImportFunction() )?
    * f1 -> MainClass()
    * f2 -> ( TypeDeclaration() )*
    * f3 -> <EOF>
    */
   public R visit(Goal n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "import"
    * f1 -> "java.util.function.Function"
    * f2 -> ";"
    */
   public R visit(ImportFunction n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> "public"
    * f4 -> "static"
    * f5 -> "void"
    * f6 -> "main"
    * f7 -> "("
    * f8 -> "String"
    * f9 -> "["
    * f10 -> "]"
    * f11 -> Identifier()
    * f12 -> ")"
    * f13 -> "{"
    * f14 -> PrintStatement()
    * f15 -> "}"
    * f16 -> "}"
    */
   public R visit(MainClass n, A argu) {
      System.out.println("MAIN");

      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      n.f7.accept(this, argu);
      n.f8.accept(this, argu);
      n.f9.accept(this, argu);
      n.f10.accept(this, argu);
      n.f11.accept(this, argu);
      n.f12.accept(this, argu);
      n.f13.accept(this, argu);
      n.f14.accept(this, argu);
      n.f15.accept(this, argu);
      n.f16.accept(this, argu);
      
      System.out.println("END\n");
      return _ret;
   }

   /**
    * f0 -> ClassDeclaration()
    *       | ClassExtendsDeclaration()
    */
   public R visit(TypeDeclaration n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> ( VarDeclaration() )*
    * f4 -> ( MethodDeclaration() )*
    * f5 -> "}"
    */
   public R visit(ClassDeclaration n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String _className = (String)n.f1.accept(this, argu);
      currClass = symbolTable.get(_className);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      currClass = null;
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "extends"
    * f3 -> Identifier()
    * f4 -> "{"
    * f5 -> ( VarDeclaration() )*
    * f6 -> ( MethodDeclaration() )*
    * f7 -> "}"
    */
   public R visit(ClassExtendsDeclaration n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String _className = (String)n.f1.accept(this, argu);
      currClass = symbolTable.get(_className);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      n.f7.accept(this, argu);
      currClass = null;
      return _ret;
   }

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    * f2 -> ";"
    */
   public R visit(VarDeclaration n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String _varName = (String)n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      if (currMethod != null) {
          currMethod.varToTemp.put(_varName, genTemp());
      }
      return _ret;
   }

   /**
    * f0 -> "public"
    * f1 -> Type()
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( FormalParameterList() )?
    * f5 -> ")"
    * f6 -> "{"
    * f7 -> ( VarDeclaration() )*
    * f8 -> ( Statement() )*
    * f9 -> "return"
    * f10 -> Expression()
    * f11 -> ";"
    * f12 -> "}"
    */
   public R visit(MethodDeclaration n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String _methodName = (String)n.f2.accept(this, argu);
      currMethod = currClass.method.get(_methodName);

      String _functionLabel = currClass.name + "_" + _methodName;
      int _noOfArgs = currMethod.paramList.size() + 1;
      System.out.println(_functionLabel + "[" + _noOfArgs + "]");
      System.out.println("BEGIN");

      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      n.f7.accept(this, argu);
      n.f8.accept(this, argu);
      n.f9.accept(this, argu);
      System.out.println("RETURN ");
      String _retExp = (String)n.f10.accept(this, argu);
      n.f11.accept(this, argu);
      n.f12.accept(this, argu);

      System.out.println("END\n");

      currMethod = null;
      parameterIndex = 1;
      return _ret;
   }

   /**
    * f0 -> FormalParameter()
    * f1 -> ( FormalParameterRest() )*
    */
   public R visit(FormalParameterList n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    */
   public R visit(FormalParameter n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String _parameter = (String)n.f1.accept(this, argu);
      currMethod.varToTemp.put(_parameter, "TEMP " + parameterIndex);
      parameterIndex++;
      return _ret;
   }

   /**
    * f0 -> ","
    * f1 -> FormalParameter()
    */
   public R visit(FormalParameterRest n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ArrayType()
    *       | BooleanType()
    *       | IntegerType()
    *       | Identifier()
    *       | LambdaType()
    */
   public R visit(Type n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "int"
    * f1 -> "["
    * f2 -> "]"
    */
   public R visit(ArrayType n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "boolean"
    */
   public R visit(BooleanType n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "int"
    */
   public R visit(IntegerType n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "Function"
    * f1 -> "<"
    * f2 -> Identifier()
    * f3 -> ","
    * f4 -> Identifier()
    * f5 -> ">"
    */
   public R visit(LambdaType n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Block()
    *       | AssignmentStatement()
    *       | ArrayAssignmentStatement()
    *       | IfStatement()
    *       | WhileStatement()
    *       | PrintStatement()
    */
   public R visit(Statement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "{"
    * f1 -> ( Statement() )*
    * f2 -> "}"
    */
   public R visit(Block n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> "="
    * f2 -> Expression()
    * f3 -> ";"
    */
   public R visit(AssignmentStatement n, A argu) {
      R _ret=null;
      String _var = (String)n.f0.accept(this, argu);
      n.f1.accept(this, argu);

      if (currMethod.varToTemp.containsKey(_var)) {
          String t2 = currMethod.varToTemp.get(_var);
          System.out.println("    MOVE " + t2);
          String t1 = (String)n.f2.accept(this, argu);
          n.f3.accept(this, argu);
      }
      else {
          String _fieldName = getDeclClass(_var) + "_" + _var;
          int _index = memLayout.get(currClass.name).fields.get(_fieldName);
          System.out.println("    HSTORE TEMP 0 " + _index);
          String t1 = (String)n.f2.accept(this, argu);
          n.f3.accept(this, argu);
      }
      return _ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> "["
    * f2 -> Expression()
    * f3 -> "]"
    * f4 -> "="
    * f5 -> Expression()
    * f6 -> ";"
    */
   public R visit(ArrayAssignmentStatement n, A argu) {
      R _ret=null;
      String _var = (String)n.f0.accept(this, argu);
      n.f1.accept(this, argu);

      String t = new String();
      if (currMethod.varToTemp.containsKey(_var)) {
          t = currMethod.varToTemp.get(_var);
      }
      else {
          t = genTemp();
          String _fieldName = getDeclClass(_var) + "_" + _var;
          int _index = memLayout.get(currClass.name).fields.get(_fieldName);

          System.out.println("    HLOAD " + t + " TEMP 0 " + _index);
      }
      String t_i = genTemp();
      System.out.println("    MOVE " + t_i + " PLUS " + t + " TIMES PLUS ");
      String i = (String)n.f2.accept(this, argu);
      System.out.println(" 1 4 ");
      System.out.println("    HSTORE " + t_i + " 0 ");
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      String t1 = (String)n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> IfthenElseStatement()
    *       | IfthenStatement()
    */
   public R visit(IfStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "if"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public R visit(IfthenStatement n, A argu) {
      String L_end = genLabel();

      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);

      System.out.println("    CJUMP ");
      String condition = (String)n.f2.accept(this, argu);
      System.out.println(" " + L_end);
      n.f3.accept(this, argu);

      n.f4.accept(this, argu);

      System.out.println(L_end + " NOOP");
      return _ret;
   }

   /**
    * f0 -> "if"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    * f5 -> "else"
    * f6 -> Statement()
    */
   public R visit(IfthenElseStatement n, A argu) {
      String L_else = genLabel();
      String L_end = genLabel();

      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);

      System.out.println("    CJUMP ");
      String condition = (String)n.f2.accept(this, argu);
      System.out.println(" " + L_else);
      n.f3.accept(this, argu);
      
      n.f4.accept(this, argu);

      System.out.println("    JUMP " + L_end);
      System.out.println(L_else + " NOOP");

      n.f5.accept(this, argu);
      n.f6.accept(this, argu);

      System.out.println(L_end + " NOOP");
      return _ret;
   }

   /**
    * f0 -> "while"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public R visit(WhileStatement n, A argu) {
      String L_while = genLabel();
      String L_end = genLabel();

      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);

      System.out.println(L_while + " NOOP");
      System.out.println("    CJUMP ");
      String condition = (String)n.f2.accept(this, argu);
      System.out.println(" " + L_end);
      n.f3.accept(this, argu);

      n.f4.accept(this, argu);

      System.out.println("    JUMP " + L_while);
      System.out.println(L_end + " NOOP");
      return _ret;
   }

   /**
    * f0 -> "System.out.println"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> ";"
    */
   public R visit(PrintStatement n, A argu) {
      System.out.println("PRINT");

      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> OrExpression()
    *       | AndExpression()
    *       | CompareExpression()
    *       | neqExpression()
    *       | AddExpression()
    *       | MinusExpression()
    *       | TimesExpression()
    *       | DivExpression()
    *       | ArrayLookup()
    *       | ArrayLength()
    *       | MessageSend()
    *       | LambdaExpression()
    *       | PrimaryExpression()
    */
   public R visit(Expression n, A argu) {
      R _ret = n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "("
    * f1 -> Identifier()
    * f2 -> ")"
    * f3 -> "->"
    * f4 -> Expression()
    */
   public R visit(LambdaExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "&&"
    * f2 -> PrimaryExpression()
    */
   public R visit(AndExpression n, A argu) {
      String t = genTemp();

      String L_else = genLabel();
      String L_end = genLabel();

      R _ret = (R)t;
      
      System.out.println("BEGIN");
      System.out.println("    CJUMP ");
      String t1 = (String)n.f0.accept(this, argu);
      System.out.println(" " + L_else);
      n.f1.accept(this, argu);
      System.out.println("    CJUMP ");
      String t2 = (String)n.f2.accept(this, argu);
      System.out.println(" " + L_else);
      System.out.println("    MOVE " + t + " 1");
      System.out.println("    JUMP " + L_end);
      System.out.println(L_else + " NOOP");
      System.out.println("    MOVE " + t + " 0");
      System.out.println(L_end + " NOOP");
      System.out.println("    RETURN " + t);
      System.out.println("END");
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "||"
    * f2 -> PrimaryExpression()
    */
   public R visit(OrExpression n, A argu) {
      String t = genTemp();

      String L_elseif = genLabel();
      String L_else = genLabel();
      String L_end = genLabel();
 
      R _ret = (R)t;

      System.out.println("BEGIN");
      System.out.println("    CJUMP ");
      String t1 = (String)n.f0.accept(this, argu);
      System.out.println(" " + L_elseif);
      n.f1.accept(this, argu);
      System.out.println("    MOVE " + t + " 1");
      System.out.println("    JUMP " + L_end);
      System.out.println(L_elseif + " NOOP");
      System.out.println("    CJUMP ");
      String t2 = (String)n.f2.accept(this, argu);
      System.out.println(" " + L_else);
      System.out.println("    MOVE " + t + " 1");
      System.out.println("    JUMP " + L_end);
      System.out.println(L_else + " NOOP");
      System.out.println("    MOVE " + t + " 0");
      System.out.println(L_end + " NOOP");
      System.out.println("    RETURN " + t);
      System.out.println("END");

      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "<="
    * f2 -> PrimaryExpression()
    */
   public R visit(CompareExpression n, A argu) {
      String t = genTemp();

      R _ret = (R)t;

      System.out.println("BEGIN");
      System.out.println("    MOVE " + t + " LE ");
      String t1 = (String)n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String t2 = (String)n.f2.accept(this, argu);
      System.out.println("    RETURN " + t);
      System.out.println("END");
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "!="
    * f2 -> PrimaryExpression()
    */
   public R visit(neqExpression n, A argu) {
      String t = genTemp();

      R _ret = (R)t;

      System.out.println("BEGIN");
      System.out.println("    MOVE " + t + " NE ");
      String t1 = (String)n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String t2 = (String)n.f2.accept(this, argu);
      System.out.println("    RETURN " + t);
      System.out.println("END");
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "+"
    * f2 -> PrimaryExpression()
    */
   public R visit(AddExpression n, A argu) {
      String t = genTemp();

      R _ret = (R)t;

      System.out.println("BEGIN");
      System.out.println("    MOVE " + t + " PLUS ");
      String t1 = (String)n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String t2 = (String)n.f2.accept(this, argu);
      System.out.println("    RETURN " + t);
      System.out.println("END");
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "-"
    * f2 -> PrimaryExpression()
    */
   public R visit(MinusExpression n, A argu) {
      String t = genTemp();

      R _ret = (R)t;

      System.out.println("BEGIN");
      System.out.println("    MOVE " + t + " MINUS ");
      String t1 = (String)n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String t2 = (String)n.f2.accept(this, argu);
      System.out.println("    RETURN " + t);
      System.out.println("END");
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "*"
    * f2 -> PrimaryExpression()
    */
   public R visit(TimesExpression n, A argu) {
      String t = genTemp();

      R _ret = (R)t;

      System.out.println("BEGIN");
      System.out.println("    MOVE " + t + " TIMES ");
      String t1 = (String)n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String t2 = (String)n.f2.accept(this, argu);
      System.out.println("    RETURN " + t);
      System.out.println("END");
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "/"
    * f2 -> PrimaryExpression()
    */
   public R visit(DivExpression n, A argu) {
      String t = genTemp();

      R _ret = (R)t;

      System.out.println("BEGIN");
      System.out.println("    MOVE " + t + " DIV ");
      String t1 = (String)n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String t2 = (String)n.f2.accept(this, argu);
      System.out.println("    RETURN " + t);
      System.out.println("END");
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "["
    * f2 -> PrimaryExpression()
    * f3 -> "]"
    */
   public R visit(ArrayLookup n, A argu) {
      String t = genTemp();

      R _ret = (R)t;

      System.out.println("BEGIN");
      String t2 = genTemp();
      System.out.println("    MOVE " + t2 + " PLUS ");
      String t1 = (String)n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      System.out.println(" TIMES PLUS ");
      String i = (String)n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      System.out.println(" 1 4");
      System.out.println("    HLOAD " + t + " " + t2 + " 0");
      System.out.println("    RETURN " + t);
      System.out.println("END");
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "."
    * f2 -> "length"
    */
   public R visit(ArrayLength n, A argu) {
      String t = genTemp();

      R _ret = (R)t;

      System.out.println("BEGIN");
      System.out.println("    HLOAD " + t + " ");
      String t1 = (String)n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      System.out.println(" 0");
      System.out.println("    RETURN " + t);
      System.out.println("END");
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "."
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( ExpressionList() )?
    * f5 -> ")"
    */
   public R visit(MessageSend n, A argu) {
      String t = genTemp();
      Attributes a = new Attributes();

      R _ret = (R)t;

      String t2 = genTemp();
      String t3 = genTemp();

      System.out.println("BEGIN");
      System.out.println("    MOVE " + t);
      System.out.println("    CALL");
      System.out.println("BEGIN");
      System.out.println("    HLOAD " + t2 + " ");
      String t1 = (String)n.f0.accept(this, (A)a);
      n.f1.accept(this, argu);
      System.out.println(" 0");
      String _methodName = (String)n.f2.accept(this, argu);
      n.f3.accept(this, argu);

      String _type = a.type;
      int _index = memLayout.get(_type).vtable.get(_methodName);
      System.out.println("    HLOAD " + t3 + " " + t2 + " " + _index);
      System.out.println("    RETURN " + t3);
      System.out.println("END");
      System.out.print("( " + t1 + " ");

      n.f4.accept(this, argu);
      n.f5.accept(this, argu);

      System.out.println(")");
      System.out.println("    RETURN " + t);
      System.out.println("END");
      if (argu != null && !paramFlag) {
          Attributes _a = (Attributes)argu;
          Method _method = getMethod(_type, _methodName);
          if (_method != null) {
              _a.type = _method.returnType;
          }
      }
      return _ret;
   }

   /**
    * f0 -> Expression()
    * f1 -> ( ExpressionRest() )*
    */
   public R visit(ExpressionList n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ","
    * f1 -> Expression()
    */
   public R visit(ExpressionRest n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> IntegerLiteral()
    *       | TrueLiteral()
    *       | FalseLiteral()
    *       | Identifier()
    *       | ThisExpression()
    *       | ArrayAllocationExpression()
    *       | AllocationExpression()
    *       | NotExpression()
    *       | BracketExpression()
    */
   public R visit(PrimaryExpression n, A argu) {
      R _ret = n.f0.accept(this, argu);
      if (isIdentifier((String)_ret)) {
          String _var = (String)_ret;
          if (currMethod.varToTemp.containsKey(_var)) {
              _ret = (R)currMethod.varToTemp.get(_var);
              System.out.println((String)_ret);
          }
          else {
              String _fieldName = getDeclClass(_var) + "_" + _var;
              int _index = memLayout.get(currClass.name).fields.get(_fieldName);

              String t = genTemp();
              System.out.println("BEGIN");
              System.out.println("    HLOAD " + t + " TEMP 0 " + _index);
              System.out.println("    RETURN " + t);
              System.out.println("END");
              _ret = (R)t;
          }
      }
      return _ret;
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public R visit(IntegerLiteral n, A argu) {
      R _ret = (R)n.f0.toString();
      System.out.println((String)_ret);
      return _ret;
   }

   /**
    * f0 -> "true"
    */
   public R visit(TrueLiteral n, A argu) {
      R _ret = (R)"1";
      n.f0.accept(this, argu);
      System.out.println("1");
      return _ret;
   }

   /**
    * f0 -> "false"
    */
   public R visit(FalseLiteral n, A argu) {
      R _ret = (R)"0";
      n.f0.accept(this, argu);
      System.out.println("0");
      return _ret;
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(Identifier n, A argu) {
      R _ret = (R)n.f0.toString();
      if (argu != null && !paramFlag) {
          Attributes _a = (Attributes)argu;
          _a.type = getIdentifierType((String)_ret);
      }
      return _ret;
   }

   /**
    * f0 -> "this"
    */
   public R visit(ThisExpression n, A argu) {
      String t = genTemp();
      System.out.println("BEGIN");
      System.out.println("    MOVE " + t + " TEMP 0");
      System.out.println("    RETURN " + t);
      System.out.println("END");

      R _ret = (R)t;
      n.f0.accept(this, argu);
      if (argu != null && !paramFlag) {
          Attributes _a = (Attributes)argu;
          _a.type = currClass.name;
      }
      return _ret;
   }

   /**
    * f0 -> "new"
    * f1 -> "int"
    * f2 -> "["
    * f3 -> Expression()
    * f4 -> "]"
    */
   public R visit(ArrayAllocationExpression n, A argu) {
      String t = genTemp();

      R _ret = (R)t;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);

      String L_while = genLabel();
      String L_end = genLabel();

      String t1 = genTemp();
      String i = genTemp();

      System.out.println("BEGIN");
      System.out.println("    MOVE " + t);
      System.out.println("BEGIN");
      System.out.println("    MOVE " + t1 + " HALLOCATE TIMES PLUS ");
      String sz = (String)n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      System.out.println(" 1 4");
      System.out.println("    HSTORE " + t1 + " 0 " + sz);

      System.out.println("    MOVE " + i + " 4");
      System.out.println(L_while + " NOOP");
      System.out.println("    CJUMP LE " + i + " TIMES " + sz + " 4 " + L_end);
      String t2 = genTemp();
      System.out.println("    MOVE " + t2 + " PLUS " + t1 + " " + i);
      System.out.println("    HSTORE " + t2 + " 0 " + " 0");
      System.out.println("    MOVE " + i + " PLUS " + i + " 4");
      System.out.println("    JUMP " + L_while);
      System.out.println("    JUMP " + L_end);

      System.out.println(L_end + " NOOP");
      System.out.println("    RETURN " + t1);

      System.out.println("END");
      System.out.println("    RETURN " + t);
      System.out.println("END");
      return _ret;
   }

   /**
    * f0 -> "new"
    * f1 -> Identifier()
    * f2 -> "("
    * f3 -> ")"
    */
   public R visit(AllocationExpression n, A argu) {
      String t = genTemp();
      
      String t1 = genTemp();
      String i = genTemp();
      String t2 = genTemp();

      String L_while = genLabel();
      String L_end = genLabel();
      String L_return = genLabel();

      R _ret = (R)t;
      n.f0.accept(this, argu);
      String _type = (String)n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      
      ClassMemLayout _typeLayout = memLayout.get(_type);
      int sz1 = (_typeLayout.fields.size() + 1) * 4; // size of the main array
      int sz2 = _typeLayout.vtable.size() * 4;       // size of the vtable 
      
      System.out.println("BEGIN");
      System.out.println("    MOVE " + t);
      System.out.println("BEGIN");
      System.out.println("    MOVE " + t1 + " HALLOCATE " + sz1); // main array

      System.out.println("    MOVE " + i + " 0");
      System.out.println(L_while + " NOOP");
      System.out.println("    CJUMP LE " + i + " MINUS " + sz1 + " 1 " + L_end);
      String t3 = genTemp();
      System.out.println("    MOVE " + t3 + " PLUS " + t1 + " " + i);
      System.out.println("    HSTORE " + t3 + " 0 " + " 0");
      System.out.println("    MOVE " + i + " PLUS " + i + " 4");
      System.out.println("    JUMP " + L_while);

      System.out.println(L_end + " NOOP");
      System.out.println("    CJUMP LE 4 " + sz2 + " " + L_return);
      System.out.println("    MOVE " + t2 + " HALLOCATE " + sz2); // vtable
      for (Map.Entry<String, Integer> entry : _typeLayout.vtable.entrySet()) {
          String _label = _typeLayout.declClass.get(entry.getKey()) + "_" + entry.getKey();
          Integer _index = entry.getValue();
          System.out.println("    HSTORE " + t2 + " " + _index + " " + _label);
      }
      System.out.println("    HSTORE " + t1 + " 0 " + t2);

      System.out.println(L_return + " NOOP");
      System.out.println("    RETURN " + t1);
      System.out.println("END");
      System.out.println("    RETURN " + t);
      System.out.println("END");
      if (argu != null && !paramFlag) {
          Attributes _a = (Attributes)argu;
          _a.type = _type;
      }
      return _ret;
   }

   /**
    * f0 -> "!"
    * f1 -> Expression()
    */
   public R visit(NotExpression n, A argu) {
      String t = genTemp();

      String L_else = genLabel();
      String L_end = genLabel();

      R _ret = (R)t;
      n.f0.accept(this, argu);

      System.out.println("BEGIN");
      System.out.println("    MOVE " + t);
      System.out.println("BEGIN");
      System.out.println("    CJUMP ");
      String exp = (String)n.f1.accept(this, argu);
      System.out.println(" " + L_else);
      System.out.println("    MOVE " + t + " 0");
      System.out.println("    JUMP " + L_end);
      System.out.println(L_else + " NOOP");
      System.out.println("    MOVE " + t + " 1");
      System.out.println(L_end + " NOOP");
      System.out.println("    RETURN " + t);
      System.out.println("END");
      System.out.println("    RETURN " + t);
      System.out.println("END");
      return _ret;
   }

   /**
    * f0 -> "("
    * f1 -> Expression()
    * f2 -> ")"
    */
   public R visit(BracketExpression n, A argu) {
      String _ret = new String();
      n.f0.accept(this, argu);
      _ret = (String)n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return (R)_ret;
   }

}
